In [1]:
import os
import pandas as pd

### Check intersection between HVGs and LINCs

In [2]:
wkdir= "/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/"
data_year = "2020"
cell_name = "BC3C"

data_dir = os.path.join(wkdir,"00_outputs_" + data_year + "_" + cell_name)
data_file = os.path.join(data_dir, "Data_norm_" + data_year + "_" + cell_name+ ".xlsx")
Data_norm = pd.read_excel(data_file, index_col = 0)
display(Data_norm)

genes_list = Data_norm.columns.to_list()
print("Landmark genes in LINCS data:", len(genes_list), genes_list)

,AARS,ABCB6,ABCC5,ABCF1,ABCF3,ABHD4,ABHD6,ABL1,ACAA1,ACAT2,...,ZMIZ1,ZMYM2,ZNF131,ZNF274,ZNF318,ZNF395,ZNF451,ZNF586,ZNF589,ZW10
ASG002_BC3C_24H:A03,-0.191254,-0.055246,0.039596,-0.256266,-0.040419,-0.590523,-0.159396,-0.074319,0.457981,0.409608,...,0.543203,0.494266,-0.011923,-0.225931,0.285054,-0.775246,0.166031,-0.024873,0.238723,0.284204
ASG002_BC3C_24H:A04,-0.265754,-0.317496,0.118696,-0.136665,-0.301569,-0.403023,0.124804,-0.036470,0.311931,0.660457,...,-0.565096,-0.088634,0.122977,-0.047931,0.141804,0.129054,-0.028819,-0.028773,-0.253627,-0.752646
ASG002_BC3C_24H:A05,-0.181954,-0.081597,-0.210304,1.559535,-0.019019,-0.457423,0.071404,0.074080,-0.356119,0.498808,...,0.226104,-0.228034,-0.121023,-0.075331,-0.133146,0.355054,0.022831,-0.084073,0.283123,-0.894896
ASG002_BC3C_24H:A06,0.033446,0.042404,-0.150154,-0.093165,0.053180,-0.053823,0.087704,0.167681,-0.601569,0.383308,...,-0.608596,-0.228835,0.072777,0.082970,-0.570996,2.847754,-0.211670,-0.067273,0.081723,0.338704
ASG002_BC3C_24H:J13,0.204446,0.180704,0.089096,-0.054666,0.053381,0.044877,-0.277396,-0.157419,0.535681,-3.933493,...,-0.318397,0.122265,-0.134323,-0.088931,-0.067996,-0.515847,-0.005069,0.067527,0.002223,0.204904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MOAR012_BC3C_24H:P20,0.647151,0.211700,-0.979200,0.597350,-0.375751,0.388300,0.394524,0.120151,-0.166775,-1.129125,...,-1.598475,-0.552750,0.515151,0.120800,0.082675,0.529700,0.383225,-0.207225,2.268450,-1.248500
MOAR012_BC3C_24H:P21,0.171800,0.046300,-0.145550,-0.295150,0.030849,0.420951,0.222075,0.179800,0.274724,-0.423975,...,-1.650575,0.203600,-0.003250,-0.064800,-0.037675,0.076499,0.201825,0.416875,0.287450,-0.971700
MOAR012_BC3C_24H:P22,0.648700,0.058749,-0.031700,0.408249,-0.753950,0.332200,-0.357525,-0.107650,-0.213575,0.074225,...,0.127625,0.031600,0.103250,-0.249600,0.046375,1.486200,0.440325,0.090075,-0.031650,-0.944300
MOAR012_BC3C_24H:P23,0.090499,-0.469300,-0.611800,0.873550,-0.788450,-0.097199,-0.366575,-0.490600,-0.624675,-0.009275,...,0.054676,-0.596050,0.084600,0.444700,0.431375,-0.921501,0.044926,0.716076,-0.000900,-1.106700
MOAR012_BC3C_24H:P24,0.204801,-1.388700,-0.283400,0.744750,-1.431150,-0.518100,-0.002174,-0.096200,1.198824,0.138525,...,-0.123474,-0.486500,0.049901,-0.598100,-0.259925,0.088650,-0.242075,0.195575,-0.038300,-1.149900

Landmark genes in LINCS data: 978 ['AARS', 'ABCB6', 'ABCC5', 'ABCF1', 'ABCF3', 'ABHD4', 'ABHD6', 'ABL1', 'ACAA1', 'ACAT2', 'ACBD3', 'ACD', 'ACLY', 'ACOT9', 'ADAM10', 'ADAT1', 'ADGRE5', 'ADGRG1', 'ADH5', 'ADI1', 'ADO', 'ADRB2', 'AGL', 'AKAP8', 'AKAP8L', 'AKR7A2', 'AKT1', 'ALAS1', 'ALDH7A1', 'ALDOA', 'ALDOC', 'AMDHD2', 'ANKRD10', 'ANO10', 'ANXA7', 'APBB2', 'APOE', 'APP', 'APPBP2', 'ARFIP2', 'ARHGAP1', 'ARHGEF12', 'ARHGEF2', 'ARID4B', 'ARID5B', 'ARL4C', 'ARNT2', 'ARPP19', 'ASAH1', 'ASCC3', 'ATF1', 'ATF5', 'ATF6', 'ATG3', 'ATMIN', 'ATP11B', 'ATP1B1', 'ATP2C1', 'ATP6V0B', 'ATP6V1D', 'AURKA', 'AURKB', 'AXIN1', 'B4GAT1', 'BACE2', 'BAD', 'BAG3', 'BAMBI', 'BAX', 'BCL2', 'BCL7B', 'BDH1', 'BECN1', 'BHLHE40', 'BID', 'BIRC2', 'BIRC5', 'BLCAP', 'BLMH', 'BLVRA', 'BMP4', 'BNIP3', 'BNIP3L', 'BPHL', 'BRCA1', 'BTK', 'BUB1B', 'BZW2', 'C2CD2', 'C2CD2L', 'C2CD5', 'C5', 'CAB39', 'CALM3', 'CALU', 'CAMSAP2', 'CANT1', 'CAPN1', 'CARMIL1', 'CASC3', 'CASK', 'CASP10', 'CASP2', 'CASP3', 'CASP7', 'CAST', 'CAT', 'CBLB', 'CBR1', 'CBR3', 'CCDC85B', 'CCDC86', 'CCDC92', 'CCL2', 'CCNA1', 'CCNA2', 'CCNB1', 'CCNB2', 'CCND1', 'CCND3', 'CCNE2', 'CCNF', 'CCNH', 'CCP110', 'CD320', 'CD40', 'CD44', 'CD58', 'CDC20', 'CDC25A', 'CDC25B', 'CDC42', 'CDC45', 'CDCA4', 'CDH3', 'CDK1', 'CDK19', 'CDK2', 'CDK4', 'CDK5R1', 'CDK6', 'CDK7', 'CDKN1A', 'CDKN1B', 'CDKN2A', 'CEBPA', 'CEBPD', 'CEBPZ', 'CEMIP2', 'CENPE', 'CEP57', 'CERK', 'CETN3', 'CFLAR', 'CGRRF1', 'CHAC1', 'CHEK1', 'CHEK2', 'CHERP', 'CHIC2', 'CHMP4A', 'CHMP6', 'CHN1', 'CHP1', 'CIAO3', 'CIAPIN1', 'CIRBP', 'CISD1', 'CLIC4', 'CLPX', 'CLSTN1', 'CLTB', 'CLTC', 'CNDP2', 'CNOT4', 'CNPY3', 'COASY', 'COG2', 'COG4', 'COG7', 'COL1A1', 'COL4A1', 'COPB2', 'COPS7A', 'COQ8A', 'CORO1A', 'CPNE3', 'CPSF4', 'CREB1', 'CREG1', 'CRELD2', 'CRK', 'CRKL', 'CRTAP', 'CRYZ', 'CSK', 'CSNK1A1', 'CSNK1E', 'CSNK2A2', 'CSRP1', 'CTNNAL1', 'CTNND1', 'CTSD', 'CTSL', 'CTTN', 'CXCL2', 'CXCR4', 'CYB561', 'CYCS', 'CYTH1', 'DAG1', 'DAXX', 'DCK', 'DCTD', 'DCUN1D4', 'DDB2', 'DDIT4', 'DDR1', 'DDX10', 'DDX42', 'DECR1', 'DENND2D', 'DERA', 'DFFA', 'DFFB', 'DHDDS', 'DHRS7', 'DHX29', 'DIPK1A', 'DLD', 'DMAC2L', 'DMTF1', 'DNAJA3', 'DNAJB1', 'DNAJB2', 'DNAJB6', 'DNAJC15', 'DNM1', 'DNM1L', 'DNMT1', 'DNMT3A', 'DNTTIP2', 'DPH2', 'DRAP1', 'DSG2', 'DUSP11', 'DUSP14', 'DUSP22', 'DUSP3', 'DUSP4', 'DUSP6', 'DYNLT3', 'DYRK3', 'E2F2', 'EAPP', 'EBNA1BP2', 'EBP', 'ECD', 'ECH1', 'EDEM1', 'EDN1', 'EED', 'EFCAB14', 'EGF', 'EGFR', 'EGR1', 'EIF4EBP1', 'EIF4G1', 'EIF5', 'ELAC2', 'ELAVL1', 'ELOVL6', 'ELP1', 'EML3', 'ENOPH1', 'ENOSF1', 'EPB41L2', 'EPHA3', 'EPHB2', 'EPN2', 'EPRS', 'ERBB2', 'ERBB3', 'ERO1A', 'ETFB', 'ETS1', 'ETV1', 'EVL', 'EXOSC4', 'EXT1', 'EZH2', 'FAH', 'FAIM', 'FAM20B', 'FAM57A', 'FAS', 'FASTKD5', 'FAT1', 'FBXL12', 'FBXO11', 'FBXO21', 'FBXO7', 'FCHO1', 'FDFT1', 'FEZ2', 'FGFR2', 'FGFR4', 'FHL2', 'FIS1', 'FKBP14', 'FKBP4', 'FOS', 'FOSL1', 'FOXJ3', 'FOXO3', 'FOXO4', 'FPGS', 'FRS2', 'FSD1', 'FUT1', 'FYN', 'FZD1', 'FZD7', 'G3BP1', 'GAA', 'GABPB1', 'GADD45A', 'GADD45B', 'GALE', 'GAPDH', 'GATA2', 'GATA3', 'GDPD5', 'GFOD1', 'GFPT1', 'GHR', 'GLI2', 'GLOD4', 'GLRX', 'GMNN', 'GNA11', 'GNA15', 'GNAI1', 'GNAI2', 'GNAS', 'GNB5', 'GNPDA1', 'GOLT1B', 'GPATCH8', 'GPC1', 'GPER1', 'GRB10', 'GRB7', 'GRN', 'GRWD1', 'GSTM2', 'GSTZ1', 'GTF2A2', 'GTF2E2', 'GTPBP8', 'H2AFV', 'HACD3', 'HADH', 'HAT1', 'HDAC2', 'HDAC6', 'HDGFL3', 'HEATR1', 'HEBP1', 'HERC6', 'HERPUD1', 'HES1', 'HIF1A', 'HIST1H2BK', 'HIST2H2BE', 'HK1', 'HLA-DMA', 'HLA-DRA', 'HMG20B', 'HMGA2', 'HMGCR', 'HMGCS1', 'HMOX1', 'HOMER2', 'HOOK2', 'HOXA10', 'HOXA5', 'HPRT1', 'HS2ST1', 'HSD17B10', 'HSD17B11', 'HSPA1A', 'HSPA4', 'HSPA8', 'HSPB1', 'HSPD1', 'HTATSF1', 'HTRA1', 'HYOU1', 'IARS2', 'ICAM1', 'ICAM3', 'ICMT', 'ID2', 'IDE', 'IER3', 'IFNAR1', 'IFRD2', 'IGF1R', 'IGF2BP2', 'IGF2R', 'IGFBP3', 'IGHMBP2', 'IKBKB', 'IKBKE', 'IKZF1', 'IL13RA1', 'IL1B', 'IL4R', 'ILK', 'INPP1', 'INPP4B', 'INSIG1', 'INTS3', 'IPO13', 'IQGAP1', 'ISOC1', 'ITFG1', 'ITGAE', 'ITGB1BP1', 'ITGB5', 'JADE2', 'JMJD6', 'JPT2', 'JUN', 'KAT6A', 'KAT6B', 'KCNK1', 'KCTD5', 'KDELR2', 'KDM3A', 'KDM5A', 'KDM5B', 'KEAP1', 'KHDC4', 'KIAA0100', 'KIAA0355', 'KIAA0753', 'KIF14', 'KIF1BP', 'KIF20A', 'KIF2C', 'KIF5C', 'KIT', 'KLHDC2', 'KLHL21', 'KLHL9', 'KTN1', 'LAGE3', 'LAMA3', 'LAP3', 'LBR', 'LGALS8', 'LGMN', 'LIG1', 'LIPA', 'LOXL1', 'LPAR2', 'LPGAT1', 'LRP10', 'LRPAP1', 'LRRC41', 'LSM5', 'LSM6', 'LSR', 'LYN', 'LYPLA1', 'LYRM1', 'MACF1', 'MALT1', 'MAMLD1', 'MAN2B1', 'MAP2K5', 'MAP3K4', 'MAP4K4', 'MAP7', 'MAPK13', 'MAPK1IP1L', 'MAPK9', 'MAPKAPK2', 'MAPKAPK3', 'MAPKAPK5', 'MAST2', 'MAT2A', 'MBNL1', 'MBNL2', 'MBOAT7', 'MBTPS1', 'MCM3', 'MCOLN1', 'MCUR1', 'ME2', 'MEF2C', 'MELK', 'MEST', 'METRN', 'MFSD10', 'MICALL1', 'MIF', 'MINDY1', 'MKNK1', 'MLEC', 'MLLT11', 'MMP1', 'MMP2', 'MNAT1', 'MOK', 'MPC2', 'MPZL1', 'MRPL12', 'MRPL19', 'MRPS16', 'MRPS2', 'MSH6', 'MSRA', 'MTA1', 'MTERF3', 'MTF2', 'MTFR1', 'MTHFD2', 'MUC1', 'MVP', 'MYBL2', 'MYC', 'MYCBP', 'MYCBP2', 'MYL9', 'MYLK', 'MYO10', 'NCAPD2', 'NCK1', 'NCK2', 'NCOA3', 'NENF', 'NET1', 'NFATC3', 'NFATC4', 'NFE2L2', 'NFIL3', 'NFKB2', 'NFKBIA', 'NFKBIB', 'NFKBIE', 'NGRN', 'NIPSNAP1', 'NISCH', 'NIT1', 'NMT1', 'NNT', 'NOL3', 'NOLC1', 'NOS3', 'NOSIP', 'NOTCH1', 'NPC1', 'NPDC1', 'NPEPL1', 'NPRL2', 'NR1H2', 'NR2F6', 'NR3C1', 'NRAS', 'NRIP1', 'NSDHL', 'NT5DC2', 'NUCB2', 'NUDCD3', 'NUDT9', 'NUP133', 'NUP62', 'NUP85', 'NUP88', 'NUP93', 'NUSAP1', 'NVL', 'ORC1', 'OXA1L', 'OXCT1', 'OXSR1', 'P4HA2', 'P4HTM', 'PACSIN3', 'PAF1', 'PAFAH1B1', 'PAFAH1B3', 'PAICS', 'PAK1', 'PAK4', 'PAK6', 'PAN2', 'PARP1', 'PARP2', 'PAX8', 'PCBD1', 'PCCB', 'PCK2', 'PCM1', 'PCMT1', 'PCNA', 'PDGFA', 'PDHX', 'PDIA5', 'PDLIM1', 'PDS5A', 'PECR', 'PEX11A', 'PFKL', 'PGAM1', 'PGM1', 'PGRMC1', 'PHGDH', 'PHKA1', 'PHKB', 'PHKG2', 'PIGB', 'PIH1D1', 'PIK3C2B', 'PIK3C3', 'PIK3CA', 'PIK3R3', 'PIK3R4', 'PIN1', 'PIP4K2B', 'PKIG', 'PLA2G15', 'PLA2G4A', 'PLCB3', 'PLEKHJ1', 'PLEKHM1', 'PLK1', 'PLOD3', 'PLP2', 'PLS1', 'PLSCR1', 'PLSCR3', 'PMAIP1', 'PMM2', 'PNKP', 'PNP', 'POLB', 'POLD4', 'POLE2', 'POLG2', 'POLR1C', 'POLR2I', 'POLR2K', 'POP4', 'PPARD', 'PPARG', 'PPIC', 'PPIE', 'PPOX', 'PPP1R13B', 'PPP2R3C', 'PPP2R5A', 'PPP2R5E', 'PRAF2', 'PRCP', 'PRKACA', 'PRKAG2', 'PRKCD', 'PRKCH', 'PRKCQ', 'PRKX', 'PROS1', 'PRPF4', 'PRR15L', 'PRR7', 'PRSS23', 'PRUNE1', 'PSIP1', 'PSMB10', 'PSMB8', 'PSMD10', 'PSMD2', 'PSMD4', 'PSMD9', 'PSME1', 'PSME2', 'PSMF1', 'PSMG1', 'PSRC1', 'PTGS2', 'PTK2', 'PTK2B', 'PTPN1', 'PTPN12', 'PTPN6', 'PTPRC', 'PTPRF', 'PTPRK', 'PUF60', 'PWP1', 'PXMP2', 'PXN', 'PYCR1', 'PYGL', 'RAB11FIP2', 'RAB21', 'RAB27A', 'RAB31', 'RAB4A', 'RAC2', 'RAD51C', 'RAD9A', 'RAE1', 'RAI14', 'RALA', 'RALB', 'RALGDS', 'RAP1GAP', 'RASA1', 'RB1', 'RBKS', 'RBM15B', 'RBM34', 'RBM6', 'REEP5', 'RELB', 'RFC2', 'RFC5', 'RFNG', 'RFX5', 'RGS2', 'RHEB', 'RHOA', 'RNF167', 'RNH1', 'RNMT', 'RNPS1', 'RPA1', 'RPA2', 'RPA3', 'RPIA', 'RPL39L', 'RPN1', 'RPP38', 'RPS5', 'RPS6', 'RPS6KA1', 'RRAGA', 'RRP12', 'RRP1B', 'RRP8', 'RRS1', 'RSU1', 'RTN2', 'RUVBL1', 'RXYLT1', 'S100A13', 'S100A4', 'SACM1L', 'SATB1', 'SCAND1', 'SCARB1', 'SCCPDH', 'SCP2', 'SCRN1', 'SCYL3', 'SDHB', 'SENP6', 'SERPINE1', 'SESN1', 'SFN', 'SGCB', 'SH3BP5', 'SHB', 'SHC1', 'SIRT3', 'SKIV2L', 'SKP1', 'SLC11A2', 'SLC1A4', 'SLC25A13', 'SLC25A14', 'SLC25A4', 'SLC25A46', 'SLC27A3', 'SLC2A6', 'SLC35A1', 'SLC35A3', 'SLC35B1', 'SLC35F2', 'SLC37A4', 'SLC5A6', 'SMAD3', 'SMARCA4', 'SMARCC1', 'SMARCD2', 'SMC1A', 'SMC3', 'SMC4', 'SMNDC1', 'SNAP25', 'SNCA', 'SNX11', 'SNX13', 'SNX6', 'SNX7', 'SOCS2', 'SORBS3', 'SOX2', 'SOX4', 'SPAG4', 'SPAG7', 'SPDEF', 'SPEN', 'SPP1', 'SPR', 'SPRED2', 'SPTAN1', 'SPTLC2', 'SQOR', 'SQSTM1', 'SRC', 'SSBP2', 'ST3GAL5', 'ST6GALNAC2', 'ST7', 'STAMBP', 'STAP2', 'STAT1', 'STAT3', 'STAT5B', 'STIMATE', 'STK10', 'STK25', 'STMN1', 'STUB1', 'STX1A', 'STX4', 'STXBP1', 'STXBP2', 'SUPV3L1', 'SUV39H1', 'SUZ12', 'SYK', 'SYNE2', 'SYNGR3', 'SYPL1', 'TARBP1', 'TATDN2', 'TBC1D31', 'TBC1D9B', 'TBP', 'TBPL1', 'TBX2', 'TBXA2R', 'TCEA2', 'TCEAL4', 'TCERG1', 'TCFL5', 'TCTA', 'TCTN1', 'TENT4A', 'TERF2IP', 'TERT', 'TES', 'TESK1', 'TEX10', 'TFAP2A', 'TFDP1', 'TGFB3', 'TGFBR2', 'THAP11', 'TIAM1', 'TICAM1', 'TIMELESS', 'TIMM17B', 'TIMM22', 'TIMM9', 'TIMP2', 'TIPARP', 'TJP1', 'TLE1', 'TLK2', 'TLR4', 'TM9SF2', 'TM9SF3', 'TMCO1', 'TMED10', 'TMEM109', 'TMEM50A', 'TMEM97', 'TNFRSF21', 'TNIP1', 'TOMM34', 'TOMM70', 'TOP2A', 'TOPBP1', 'TOR1A', 'TP53', 'TP53BP1', 'TP53BP2', 'TPD52L2', 'TPM1', 'TRAK2', 'TRAM2', 'TRAP1', 'TRAPPC3', 'TRAPPC6A', 'TRIB1', 'TRIB3', 'TRIM13', 'TRIM2', 'TSC22D3', 'TSEN2', 'TSKU', 'TSPAN3', 'TSPAN4', 'TSPAN6', 'TSTA3', 'TUBB6', 'TWF2', 'TXLNA', 'TXNDC9', 'TXNL4B', 'TXNRD1', 'UBE2A', 'UBE2C', 'UBE2J1', 'UBE2L6', 'UBE3B', 'UBE3C', 'UBQLN2', 'UBR7', 'UFM1', 'UGDH', 'USP1', 'USP14', 'USP22', 'USP6NL', 'USP7', 'UTP14A', 'VAPB', 'VAT1', 'VAV3', 'VDAC1', 'VGLL4', 'VPS28', 'VPS72', 'WASF3', 'WASHC4', 'WASHC5', 'WDR61', 'WDR7', 'WDTC1', 'WFS1', 'WIPF2', 'WRB', 'XBP1', 'XPNPEP1', 'XPO7', 'YKT6', 'YME1L1', 'YTHDF1', 'ZDHHC6', 'ZFP36', 'ZMIZ1', 'ZMYM2', 'ZNF131', 'ZNF274', 'ZNF318', 'ZNF395', 'ZNF451', 'ZNF586', 'ZNF589', 'ZW10']

In [3]:
marker_genes= ['FABP4','GPX2','KRT1','TFAP2B','ERBB4','KRT14','KRT5','KRT6A','KRT6B','KRT6C','UPK1B','UPK2','FOXA1','CDH3','GATA3','KRT19','CD24','ELF3','KRT16',
 'KRT7','TFAP2A','ERBB2','XBP1','CD44','EGFR','PPARG','KRT18','ERBB3','CYP2J2','FGFR3','UPK3B','KRT20','UPK1A','UPK3A']

In [9]:
list(set(genes_list) & set(marker_genes))

['CD44', 'CDH3', 'XBP1', 'TFAP2A', 'PPARG', 'ERBB2', 'GATA3', 'ERBB3', 'EGFR']

In [11]:
scvi_lfc = pd.read_excel('/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_svm/blca_scR_scvi_DEG.xlsx',index_col=0)

In [39]:
cluster1_t2=scvi_lfc.iloc[2000:4000]
cluster1_t2

,Unnamed: 1,Gene,proba_de,proba_not_de,bayes_factor,scale1,scale2,pseudocounts,delta,lfc_mean,...,raw_mean1,raw_mean2,non_zeros_proportion1,non_zeros_proportion2,raw_normalized_mean1,raw_normalized_mean2,is_de_fdr_0.05,comparison.1,group1,group2
comparison,,,,,,,,,,,,,,,,,,,,,
cluster1_T2 vs Rest,2003,S100A8,0.9882,0.0118,4.427785,0.018520,0.001026,0,0.25,11.116735,...,28.701602,2.676416,0.989554,0.160731,157.213465,8.685154,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2027,TCHH,0.9828,0.0172,4.045496,0.000125,0.000010,0,0.25,8.430903,...,0.189415,0.026128,0.159471,0.019526,1.146265,0.090688,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2005,LYNX1,0.9874,0.0126,4.361378,0.000520,0.000039,0,0.25,7.749890,...,0.794916,0.097591,0.384401,0.048015,4.525495,0.339901,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2016,S100A9,0.9842,0.0158,4.131819,0.019399,0.001553,0,0.25,7.666663,...,31.654944,5.028729,0.999304,0.362756,179.351834,13.862785,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2014,SERPINB4,0.9844,0.0156,4.144761,0.000427,0.000033,0,0.25,7.538958,...,0.667827,0.099672,0.388928,0.049656,3.655554,0.292484,True,cluster1_T2 vs Rest,cluster1_T2,Rest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,2092,SPOCD1,0.9760,0.0240,3.705408,0.000002,0.000237,0,0.25,-6.174197,...,0.000348,1.419374,0.000348,0.483395,0.002401,2.428690,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2066,TESC,0.9774,0.0226,3.766946,0.000003,0.000488,0,0.25,-6.383301,...,0.002437,2.383843,0.002437,0.666053,0.013217,4.831855,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2020,IGFBP2,0.9840,0.0160,4.119037,0.000003,0.001056,0,0.25,-7.289587,...,0.001741,5.539653,0.001741,0.724032,0.012602,10.003814,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2026,IGFBP5,0.9828,0.0172,4.045496,0.000002,0.000684,0,0.25,-7.476717,...,0.002089,3.806938,0.002089,0.566261,0.013906,6.441860,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2000,SPINK1,0.9912,0.0088,4.724163,0.000016,0.009093,0,0.25,-8.148858,...,0.025766,43.939101,0.013579,0.889645,0.161150,86.899691,True,cluster1_T2 vs Rest,cluster1_T2,Rest

In [33]:
print(set(scvi_lfc.iloc[2000:]['Gene'].tolist()).intersection(marker_genes))
len(set(scvi_lfc.iloc[2000:]['Gene'].tolist()).intersection(marker_genes))

{'KRT5', 'KRT20', 'UPK2', 'CD24', 'KRT14', 'GPX2', 'UPK3A', 'KRT7', 'FABP4', 'GATA3', 'UPK1B', 'UPK1A', 'KRT16', 'KRT18', 'ELF3', 'FOXA1'}

16

In [35]:
set(scvi_lfc.iloc[2000:]['Gene'].tolist()).intersection(marker_genes).tolist()

AttributeError: 'set' object has no attribute 'tolist'

In [44]:
df= cluster1_t2[cluster1_t2['Gene'].isin(['KRT5', 'KRT20', 'UPK2', 'CD24', 'KRT14', 'GPX2', 'UPK3A', 'KRT7', 'FABP4', 'GATA3', 'UPK1B', 'UPK1A', 'KRT16', 
                                      'KRT18', 'ELF3', 'FOXA1'])]
df

,Unnamed: 1,Gene,proba_de,proba_not_de,bayes_factor,scale1,scale2,pseudocounts,delta,lfc_mean,...,raw_mean1,raw_mean2,non_zeros_proportion1,non_zeros_proportion2,raw_normalized_mean1,raw_normalized_mean2,is_de_fdr_0.05,comparison.1,group1,group2
comparison,,,,,,,,,,,,,,,,,,,,,
NaN,2004,KRT14,0.9876,0.0124,4.377580,4.036402e-04,0.000038,0,0.25,5.706778,...,0.574861,0.103113,0.243733,0.056298,2.776656,0.295078,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2382,KRT5,0.9532,0.0468,3.013941,6.464737e-04,0.000156,0,0.25,5.206592,...,1.001741,0.710667,0.529944,0.253041,5.304018,1.387400,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2416,KRT16,0.9504,0.0496,2.952892,8.413281e-04,0.000168,0,0.25,2.624405,...,1.352368,0.818422,0.375696,0.255762,6.552964,1.499393,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2543,UPK1B,0.9404,0.0596,2.758650,1.770178e-04,0.000253,0,0.25,2.391312,...,0.283426,1.725632,0.230501,0.284851,1.704799,2.441607,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,3705,GPX2,0.7846,0.2154,1.292677,1.686125e-03,0.001483,0,0.25,0.348871,...,2.908774,8.101993,0.907730,0.927057,17.327736,14.815771,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,3706,FOXA1,0.7844,0.2156,1.291494,6.967909e-05,0.000097,0,0.25,-0.243316,...,0.115599,0.569102,0.109331,0.324384,0.681436,0.955933,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,3870,GATA3,0.7166,0.2834,0.927658,4.090804e-04,0.000574,0,0.25,-0.377843,...,0.719708,3.136924,0.478760,0.795935,4.134517,5.749872,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,3722,KRT7,0.7784,0.2216,1.256367,1.421626e-03,0.002201,0,0.25,-0.421537,...,2.433148,10.707666,0.854805,0.969950,14.468305,22.094540,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,3274,ELF3,0.8706,0.1294,1.906274,1.465203e-03,0.002721,0,0.25,-0.655841,...,2.588092,12.170735,0.869081,0.969710,15.170127,26.309338,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,3233,KRT18,0.8750,0.1250,1.945910,7.190239e-04,0.002159,0,0.25,-1.281258,...,1.206825,11.141725,0.645543,0.958547,7.099471,20.890239,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2869,CD24,0.9130,0.0870,2.350828,2.077393e-04,0.001633,0,0.25,-2.044621,...,0.369429,9.311460,0.265320,0.757762,2.005972,15.710639,False,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2304,UPK2,0.9592,0.0408,3.157417,7.677257e-06,0.000419,0,0.25,-2.516771,...,0.016365,3.426376,0.015669,0.255242,0.099571,4.262861,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2475,KRT20,0.9456,0.0544,2.855455,1.374083e-06,0.000079,0,0.25,-2.693248,...,0.002089,0.458467,0.002089,0.197063,0.012883,0.793333,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2305,FABP4,0.9592,0.0408,3.157417,6.906444e-06,0.000909,0,0.25,-4.372693,...,0.010097,3.993838,0.009749,0.452545,0.061422,7.356063,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2235,UPK3A,0.9642,0.0358,3.293351,1.124183e-06,0.000184,0,0.25,-4.997615,...,0.001045,1.125720,0.001045,0.290093,0.006286,1.745379,True,cluster1_T2 vs Rest,cluster1_T2,Rest
NaN,2210,UPK1A,0.9658,0.0342,3.340731,6.769570e-07,0.000329,0,0.25,-5.142361,...,0.000000,2.378161,0.000000,0.277289,0.000000,3.338034,True,cluster1_T2 vs Rest,cluster1_T2,Rest

In [42]:
#Depmap
import re
blca= pd.read_csv('/home/jing/Phd_project/project_UCD_blca/blca_DATA/blca_DATA_depmep/OmicsExpressionProteinCodingGenesTPMLogp1.csv',index_col=0)
blca.columns = [re.sub(r'\s*\(.*?\)', '', s) for s in list(blca.columns)]
blca

,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,H3C2,H3C3,AC098582.1,DUS4L-BCAP29,C8orf44-SGK3,ELOA3B,NPBWR1,ELOA3D,ELOA3,CDR1
ACH-001113,4.331992,0.000000,7.364660,2.792855,4.471187,0.028569,1.226509,3.044394,6.500005,4.739848,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.000000,0.275007,0.0,0.000000,0.000000
ACH-001289,4.567424,0.584963,7.106641,2.543496,3.504620,0.000000,0.189034,3.813525,4.221877,3.481557,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.000000,0.014355,0.0,0.000000,0.000000
ACH-001339,3.150560,0.000000,7.379118,2.333424,4.228049,0.056584,1.310340,6.687201,3.682573,3.273516,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.000000,0.084064,0.0,0.000000,0.042644
ACH-001538,5.085340,0.000000,7.154211,2.545968,3.084064,0.000000,5.868390,6.165309,4.489928,3.956986,...,0.214125,0.632268,0.298658,1.641546,0.443607,0.000000,0.028569,0.0,0.000000,0.000000
ACH-000242,6.729417,0.000000,6.537917,2.456806,3.867896,0.799087,7.208478,5.570159,7.127117,4.568032,...,1.117695,2.358959,0.084064,1.910733,0.000000,0.000000,0.464668,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000285,0.056584,0.000000,6.604368,3.266037,4.973152,0.411426,0.097611,0.704872,4.829850,5.178715,...,2.229588,0.084064,1.310340,3.039138,0.344828,0.000000,0.000000,0.0,0.475085,0.042644
ACH-002669,3.111031,0.000000,7.031329,1.541019,3.664483,0.014355,3.624101,6.805421,4.472488,4.397118,...,0.189034,0.400538,0.356144,1.327687,0.000000,0.000000,0.014355,0.0,0.000000,0.000000
ACH-001858,4.390943,0.000000,7.013239,1.887525,3.252476,0.028569,3.286881,6.902194,5.410748,3.401903,...,1.097611,0.400538,0.613532,1.992768,0.704872,0.000000,1.464668,0.0,0.000000,0.526069
ACH-001997,5.057450,0.000000,7.815191,2.538538,3.893362,0.028569,4.079805,6.971659,4.469886,3.463361,...,0.831877,0.847997,1.292782,2.153805,0.687061,0.000000,0.000000,0.0,0.000000,0.000000
ACH-000052,4.249445,0.000000,6.175724,2.319040,3.825786,0.189034,1.321928,3.538538,3.945795,4.469886,...,1.244887,1.207893,0.000000,1.956057,0.575312,0.042644,0.000000,0.0,0.176323,0.056584

In [43]:
def compute_invasiveness_score(blca, vector, vector_name='n', score_name='invasiveness'):
    """
    Compute invasiveness score via dot product between expression and gene vector.

    Parameters:
        blca (pd.DataFrame): Gene expression DataFrame (samples as rows, genes as columns).
        vector (pd.DataFrame or pd.Series): Gene weights with gene names as index.
        vector_name (str): Column name to extract from DataFrame if `vector` is a DataFrame.
        score_name (str): Name for the output score column.

    Returns:
        pd.DataFrame: DataFrame with index as blca samples and one column: score_name.
    """
    # Align vector and expression matrix by intersecting genes
    common_genes = blca.columns.intersection(vector.index)
    common_genes = common_genes.intersection(genes_list)
    print(len(common_genes))
    print(common_genes)
    vector_aligned = vector.loc[common_genes]
    print(vector_aligned)
    if isinstance(vector_aligned, pd.DataFrame):
        vector_aligned = vector_aligned[vector_name]

    blca_aligned = blca[common_genes]
    print(blca_aligned)
    # Compute dot product
    scores = blca_aligned.dot(vector_aligned)

    # Wrap in DataFrame
    score_df = pd.DataFrame(scores, columns=[score_name])
    
    return score_df

In [47]:
df.set_index('Gene',inplace=True)

In [48]:
DPD_df = compute_invasiveness_score(blca, df, vector_name='lfc_mean', score_name='invasiveness')
display(DPD_df)

1
Index(['GATA3'], dtype='object')
       Unnamed: 1  proba_de  proba_not_de  bayes_factor    scale1    scale2  \
GATA3        3870    0.7166        0.2834      0.927658  0.000409  0.000574

       pseudocounts  delta  lfc_mean  lfc_median  ...  raw_mean1  raw_mean2  \
GATA3             0   0.25 -0.377843   -0.298189  ...   0.719708   3.136924

       non_zeros_proportion1  non_zeros_proportion2  raw_normalized_mean1  \
GATA3                0.47876               0.795935              4.134517

       raw_normalized_mean2  is_de_fdr_0.05         comparison.1       group1  \
GATA3              5.749872           False  cluster1_T2 vs Rest  cluster1_T2

       group2
GATA3    Rest

[1 rows x 23 columns]
               GATA3
ACH-001113  1.117695
ACH-001289  0.378512
ACH-001339  0.214125
ACH-001538  0.565597
ACH-000242  7.076067
...              ...
ACH-000285  0.097611
ACH-002669  0.000000
ACH-001858  2.801159
ACH-001997  2.307429
ACH-000052  2.235727

[1517 rows x 1 columns]

            invasiveness
ACH-001113     -0.422314
ACH-001289     -0.143018
ACH-001339     -0.080906
ACH-001538     -0.213707
ACH-000242     -2.673644
...                  ...
ACH-000285     -0.036882
ACH-002669      0.000000
ACH-001858     -1.058399
ACH-001997     -0.871846
ACH-000052     -0.844754

[1517 rows x 1 columns]

In [51]:
cluster1_t2.set_index('Gene',inplace=True)

In [54]:
cluster1_t2

,Unnamed: 1,proba_de,proba_not_de,bayes_factor,scale1,scale2,pseudocounts,delta,lfc_mean,lfc_median,...,raw_mean1,raw_mean2,non_zeros_proportion1,non_zeros_proportion2,raw_normalized_mean1,raw_normalized_mean2,is_de_fdr_0.05,comparison.1,group1,group2
Gene,,,,,,,,,,,,,,,,,,,,,
S100A8,2003,0.9882,0.0118,4.427785,0.018520,0.001026,0,0.25,11.116735,10.915215,...,28.701602,2.676416,0.989554,0.160731,157.213465,8.685154,True,cluster1_T2 vs Rest,cluster1_T2,Rest
TCHH,2027,0.9828,0.0172,4.045496,0.000125,0.000010,0,0.25,8.430903,9.091848,...,0.189415,0.026128,0.159471,0.019526,1.146265,0.090688,True,cluster1_T2 vs Rest,cluster1_T2,Rest
LYNX1,2005,0.9874,0.0126,4.361378,0.000520,0.000039,0,0.25,7.749890,8.247373,...,0.794916,0.097591,0.384401,0.048015,4.525495,0.339901,True,cluster1_T2 vs Rest,cluster1_T2,Rest
S100A9,2016,0.9842,0.0158,4.131819,0.019399,0.001553,0,0.25,7.666663,7.763826,...,31.654944,5.028729,0.999304,0.362756,179.351834,13.862785,True,cluster1_T2 vs Rest,cluster1_T2,Rest
SERPINB4,2014,0.9844,0.0156,4.144761,0.000427,0.000033,0,0.25,7.538958,7.875496,...,0.667827,0.099672,0.388928,0.049656,3.655554,0.292484,True,cluster1_T2 vs Rest,cluster1_T2,Rest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SPOCD1,2092,0.9760,0.0240,3.705408,0.000002,0.000237,0,0.25,-6.174197,-6.582010,...,0.000348,1.419374,0.000348,0.483395,0.002401,2.428690,True,cluster1_T2 vs Rest,cluster1_T2,Rest
TESC,2066,0.9774,0.0226,3.766946,0.000003,0.000488,0,0.25,-6.383301,-7.066574,...,0.002437,2.383843,0.002437,0.666053,0.013217,4.831855,True,cluster1_T2 vs Rest,cluster1_T2,Rest
IGFBP2,2020,0.9840,0.0160,4.119037,0.000003,0.001056,0,0.25,-7.289587,-8.085510,...,0.001741,5.539653,0.001741,0.724032,0.012602,10.003814,True,cluster1_T2 vs Rest,cluster1_T2,Rest
IGFBP5,2026,0.9828,0.0172,4.045496,0.000002,0.000684,0,0.25,-7.476717,-8.018064,...,0.002089,3.806938,0.002089,0.566261,0.013906,6.441860,True,cluster1_T2 vs Rest,cluster1_T2,Rest
SPINK1,2000,0.9912,0.0088,4.724163,0.000016,0.009093,0,0.25,-8.148858,-9.094893,...,0.025766,43.939101,0.013579,0.889645,0.161150,86.899691,True,cluster1_T2 vs Rest,cluster1_T2,Rest

In [73]:
cluster1_t2_fdr = cluster1_t2[cluster1_t2['is_de_fdr_0.05'] == True]

In [86]:
DPD_df_fdr_df = compute_invasiveness_score(blca, cluster1_t2_fdr, vector_name='lfc_mean', score_name='invasiveness')
display(DPD_df_fdr_df)

73
Index(['FYN', 'LAMA3', 'MYLK', 'CDC42', 'PTGS2', 'EDN1', 'RAB21', 'CXCL2',
       'MEF2C', 'PTPRC', 'MMP2', 'AURKA', 'BIRC5', 'ICAM1', 'PHGDH', 'HMOX1',
       'DHRS7', 'HOXA5', 'LSM5', 'SERPINE1', 'RPA3', 'MEST', 'PDLIM1', 'CCL2',
       'GMNN', 'HMGCS1', 'HES1', 'ID2', 'SLC1A4', 'CDC20', 'SPP1', 'SOCS2',
       'CXCR4', 'LOXL1', 'APOE', 'TOP2A', 'CCNB1', 'PSRC1', 'CDK4', 'MYC',
       'NUSAP1', 'CENPE', 'CREG1', 'SCCPDH', 'SNCA', 'CCNA2', 'IGFBP3',
       'CDKN2A', 'PRSS23', 'SLC25A4', 'CCNB2', 'CBR3', 'PLK1', 'PRR15L',
       'DDIT4', 'PKIG', 'CLIC4', 'CDK1', 'CYCS', 'GLRX', 'STAT5B', 'UBE2C',
       'FOSL1', 'BNIP3', 'AURKB', 'GATA2', 'CRELD2', 'MUC1', 'INSIG1',
       'S100A4', 'CTNND1', 'HLA-DRA', 'HSPA1A'],
      dtype='object')
         Unnamed: 1  proba_de  proba_not_de  bayes_factor    scale1    scale2  \
FYN            2742    0.9240        0.0760      2.497979  0.000001  0.000002
LAMA3          2743    0.9240        0.0760      2.497979  0.000007  0.000021
MYLK           2184    0.9680        0.0320      3.409496  0.000003  0.000006
CDC42          2430    0.9498        0.0502      2.940236  0.005597  0.000975
PTGS2          2556    0.9390        0.0610      2.733941  0.000070  0.000030
...             ...       ...           ...           ...       ...       ...
INSIG1         2293    0.9598        0.0402      3.172858  0.000138  0.000456
S100A4         2721    0.9258        0.0742      2.523894  0.000273  0.003145
CTNND1         2621    0.9334        0.0666      2.640129  0.000369  0.000159
HLA-DRA        2650    0.9314        0.0686      2.608396  0.000167  0.000349
HSPA1A         2313    0.9584        0.0416      3.137165  0.001365  0.000653

         pseudocounts  delta  lfc_mean  lfc_median  ...  raw_mean1  raw_mean2  \
FYN                 0   0.25  1.402929    1.645311  ...   0.002786   0.007482
LAMA3               0   0.25 -1.280352   -1.437432  ...   0.014276   0.104754
MYLK                0   0.25  2.546028    2.773256  ...   0.006964   0.023407
CDC42               0   0.25  3.272702    3.548945  ...   8.920961   3.619558
PTGS2               0   0.25  2.031463    1.981387  ...   0.112117   0.116637
...               ...    ...       ...         ...  ...        ...        ...
INSIG1              0   0.25  0.564104    0.412493  ...   0.262883   1.937100
S100A4              0   0.25 -0.906609   -0.271529  ...   0.440460  12.958147
CTNND1              0   0.25  1.405957    1.510635  ...   0.631616   0.756882
HLA-DRA             0   0.25  0.270814    0.260989  ...   0.240599   1.431018
HSPA1A              0   0.25  2.961610    2.732127  ...   2.386838   3.401609

         non_zeros_proportion1  non_zeros_proportion2  raw_normalized_mean1  \
FYN                   0.002786               0.005322              0.014605
LAMA3                 0.013928               0.085187              0.076904
MYLK                  0.006964               0.007963              0.041764
CDC42                 0.997911               0.827625             52.429269
PTGS2                 0.100975               0.076144              0.656027
...                        ...                    ...                   ...
INSIG1                0.220752               0.408331              1.534035
S100A4                0.331128               0.559019              2.618519
CTNND1                0.438370               0.456786              3.656735
HLA-DRA               0.193593               0.423776              1.483235
HSPA1A                0.832173               0.515125             13.587476

         raw_normalized_mean2  is_de_fdr_0.05         comparison.1  \
FYN                  0.019602            True  cluster1_T2 vs Rest
LAMA3                0.211936            True  cluster1_T2 vs Rest
MYLK                 0.062660            True  cluster1_T2 vs Rest
CDC42                9.264897            True  cluster1_T2 vs Rest
PTGS2                0.280795            True  cluster1_T2 vs Rest
...                       ...             ...                  ...
INSIG1               3.987034            True  cluster1_T2 vs Rest
S100A4              30.220704            True  cluster1_T2 vs Rest
CTNND1               1.550529            True  cluster1_T2 vs Rest
HLA-DRA              3.148683            True  cluster1_T2 vs Rest
HSPA1A               6.591985            True  cluster1_T2 vs Rest

              group1  group2
FYN      cluster1_T2    Rest
LAMA3    cluster1_T2    Rest
MYLK     cluster1_T2    Rest
CDC42    cluster1_T2    Rest
PTGS2    cluster1_T2    Rest
...              ...     ...
INSIG1   cluster1_T2    Rest
S100A4   cluster1_T2    Rest
CTNND1   cluster1_T2    Rest
HLA-DRA  cluster1_T2    Rest
HSPA1A   cluster1_T2    Rest

[73 rows x 23 columns]
                 FYN     LAMA3      MYLK     CDC42     PTGS2      EDN1  \
ACH-001113  2.797013  2.157044  3.189034  7.344385  0.333424  4.363171
ACH-001289  7.561708  1.704872  0.411426  8.311839  0.925999  0.422233
ACH-001339  6.518378  0.505891  4.780310  7.872028  2.873813  0.356144
ACH-001538  3.273516  5.074249  4.698774  8.386466  2.084064  0.526069
ACH-000242  2.996389  3.679199  3.232661  7.636842  1.443607  2.604071
...              ...       ...       ...       ...       ...       ...
ACH-000285  4.630522  0.985500  0.275007  7.440620  0.084064  0.111031
ACH-002669  1.560715  4.633431  1.292782  6.989480  3.543496  3.518535
ACH-001858  4.814038  3.392317  6.023921  8.435587  0.659925  4.142413
ACH-001997  5.101398  7.089901  0.659925  7.706323  0.669027  5.263034
ACH-000052  3.330558  1.163499  1.111031  7.176323  1.144046  0.150560

               RAB21     CXCL2     MEF2C     PTPRC  ...     BNIP3     AURKB  \
ACH-001113  5.652486  2.485427  0.831877  0.028569  ...  3.958843  4.644433
ACH-001289  5.436961  0.000000  3.089159  0.014355  ...  4.788164  5.830103
ACH-001339  4.621173  0.356144  4.051372  0.097611  ...  4.762349  6.835545
ACH-001538  4.456806  2.498251  0.137504  0.536053  ...  3.026800  5.541639
ACH-000242  5.218394  0.124328  0.613532  0.137504  ...  2.545968  6.180108
...              ...       ...       ...       ...  ...       ...       ...
ACH-000285  5.479619  0.028569  3.493135  7.144454  ...  3.032101  6.797791
ACH-002669  5.174327  5.626439  0.443607  0.084064  ...  0.070389  6.184280
ACH-001858  4.475085  2.283922  1.327687  0.084064  ...  5.643568  6.593055
ACH-001997  5.027685  1.618239  1.104337  0.000000  ...  0.378512  6.496015
ACH-000052  5.293518  0.201634  0.790772  0.084064  ...  4.830357  7.303507

               GATA2    CRELD2      MUC1    INSIG1     S100A4    CTNND1  \
ACH-001113  2.163499  5.128046  1.310340  5.792074   6.009213  5.728193
ACH-001289  1.589763  5.580145  3.336283  6.553975   5.729281  6.908333
ACH-001339  1.367371  5.674122  1.150560  5.533875  11.335223  5.478648
ACH-001538  0.097611  2.851999  1.604071  5.000901   5.315421  6.795455
ACH-000242  4.763943  5.157448  1.910733  6.293702   6.310522  7.017365
...              ...       ...       ...       ...        ...       ...
ACH-000285  0.163499  4.427606  0.555816  6.052894   4.870365  2.589763
ACH-002669  1.765535  2.974529  6.950585  4.660495   3.877744  6.334318
ACH-001858  2.090853  4.269033  5.649041  6.895060   6.642124  6.154413
ACH-001997  0.678072  3.454176  8.003658  6.649615   4.684258  6.199672
ACH-000052  4.352617  5.964630  1.847997  5.945093   5.144046  6.432458

              HLA-DRA    HSPA1A
ACH-001113   0.263034  7.849124
ACH-001289   0.084064  4.778734
ACH-001339  10.273679  5.247168
ACH-001538   4.538538  7.664838
ACH-000242   2.077243  6.234770
...               ...       ...
ACH-000285  10.157347  1.956057
ACH-002669   0.863938  1.636915
ACH-001858   0.150560  6.972118
ACH-001997   0.565597  6.442280
ACH-000052   0.799087  6.431456

[1517 rows x 73 columns]

            invasiveness
ACH-001113    362.512018
ACH-001289    456.090871
ACH-001339    406.324130
ACH-001538    421.983629
ACH-000242    278.830318
...                  ...
ACH-000285    518.321949
ACH-002669    370.362644
ACH-001858    365.315194
ACH-001997    380.078296
ACH-000052    416.083977

[1517 rows x 1 columns]

In [87]:
cell_line_ids=['ACH-000473','ACH-000142','ACH-000593','ACH-000396','ACH-000242','ACH-000384',
               'ACH-000018','ACH-000724','ACH-001407','ACH-000753']
DPD_df_fdr= DPD_df_fdr_df.loc[cell_line_ids]
DPD_df_fdr['cell_line_name']=['RT112','CAL29','BC3C','J82','RT4','SW780','T24','HT1376','UMUC13','JMSU1']

### Actually separated basal and luminal

            invasiveness cell_line_name
ACH-000473    287.832508          RT112
ACH-000142    274.535877          CAL29
ACH-000593    352.258737           BC3C
ACH-000396    321.557905            J82
ACH-000242    278.830318            RT4
ACH-000384    344.207865          SW780
ACH-000018    381.023836            T24
ACH-000724    449.394396         HT1376
ACH-001407    400.015878         UMUC13
ACH-000753    398.294652          JMSU1

In [88]:
DPD_df_fdr.sort_values('invasiveness')

            invasiveness cell_line_name
ACH-000142    274.535877          CAL29
ACH-000242    278.830318            RT4
ACH-000473    287.832508          RT112
ACH-000396    321.557905            J82
ACH-000384    344.207865          SW780
ACH-000593    352.258737           BC3C
ACH-000018    381.023836            T24
ACH-000753    398.294652          JMSU1
ACH-001407    400.015878         UMUC13
ACH-000724    449.394396         HT1376

### Join All_data

In [56]:
stvs=pd.read_excel('/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_BC3C/ALL_DATA_2020_july_25.xlsx',
                   sheet_name='STV',index_col=0)
stvs

        blca_invasiveness  blca_oncogenesis  blca_survival
Genes
AARS             0.016052          0.078487       0.000000
ABCB6            0.001612          0.027125      -2.890931
ABCC5           -0.016742          0.002121       0.000000
ABCF1           -0.038990         -0.028959      -0.496186
ABCF3            0.023288          0.036671       0.000000
...                   ...               ...            ...
ZNF395           0.000000          0.000000       0.000000
ZNF451           0.011450          0.013403       0.000000
ZNF586           0.000000          0.000000       0.119103
ZNF589           0.000000          0.000000       0.000000
ZW10            -0.042841          0.009722       0.000000

[978 rows x 3 columns]

In [57]:
stvs['blca_basal_luminal'] = 0

In [60]:
common_idx = stvs.index.intersection(cluster1_t2.index)
stvs.loc[common_idx, 'blca_basal_luminal'] = cluster1_t2.loc[common_idx, 'lfc_mean']

/tmp/ipykernel_659634/2753322551.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.60947323 -1.45124185 -1.02163887  4.71548033 -0.1208339   2.67096925
  3.34934187 -0.57580686 -0.75581026  0.73256874  4.47131586  0.08777279
 -4.46415043  0.36272988 -1.68210876  1.10087955  0.8001467   4.62894249
  2.80239987  2.79185653  0.86372566  2.04986954  3.93493056  3.27270174
  3.606179    2.81175995 -0.59041065  5.32140827 -0.51326901  3.08210444
 -0.05806603  0.88212657  1.12293661 -1.45708489  0.14707845 -0.08196441
  0.55034137 -0.57767612  1.65878558  1.92138922  1.40595746  1.07344639
  0.43127939  2.33054495  1.60866499 -0.68667477 -2.09935379 -0.92110628
 -1.96503925  0.99738991  1.42422807  0.79505605  1.4815172   0.25768727
  0.37578148 -0.018539    0.48003125 -0.22539665 -1.95800662  0.41985267
  1.63113117  1.11596859  1.97649026  0.86447412 -0.03241801 -1.32236719
  1.99616468 -2.03851533  1.40292907 -0.82955354 -0.77754885 -1.11673212
 -5.22954845 -0.37784323 -3.2914567   2.92851472 -0.36174181 -0.74601072
 -0.02699404  0.34149659  1.52567065  0.75121224  0.27081373 -0.76259208
  2.91326261 -0.75401866  0.70584232 -2.40135074  1.02105606  2.96161032
 -1.02125835 -0.43555152  0.08240109 -1.33784497  0.32415795 -5.43853951
  1.36913443  0.56410444 -0.40566516  0.66134793 -1.28035212 -0.28800395
 -0.06222132 -2.74995613  1.40135396 -0.58008373  0.59583426 -0.22939372
 -0.33709568  2.28054833 -5.04194546 -1.43493831 -0.26436818  4.03296375
  2.29792976 -0.73602676  2.5460279  -0.49356464 -1.65876842  4.48598576
  0.02683975 -0.23396203  0.56379867 -2.39173174 -1.58530962 -2.32719851
  2.79693294  0.62644678  0.38312557 -0.58817363  1.42783749 -2.8868382
 -0.21356098  0.42369571  1.2118547   2.03146315  3.34172583  4.9658947
 -0.20151846  0.36892202  0.47726408  0.17958474  2.05321121 -1.34360826
 -0.15929697  0.11185732 -0.906609    1.6030823  -0.50317669  1.7029562
  1.00756061  3.02787948 -1.48476529  1.10465491 -3.120579   -2.08224177
 -0.30012175  0.15664321  1.40825284  2.83242607 -0.31365502 -1.22935688
  0.41048437  0.23246011 -1.22440517  0.87928152  0.68789399 -2.02237439
  4.44692278  0.38009402 -0.37772188 -0.27702966  1.07294023 -0.91766477
  0.43548086  1.57182252 -0.23455834  2.07207727  1.82216465  5.16066074
 -0.44784027 -0.79707235]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  stvs.loc[common_idx, 'blca_basal_luminal'] = cluster1_t2.loc[common_idx, 'lfc_mean']

In [64]:
pd.read_excel('/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_BC3C/ALL_DATA_2020_july_25.xlsx',
                   sheet_name='STV',index_col=0)

stvs.to_excel('/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_BC3C/merged.xlsx')

In [65]:
stvs

        blca_invasiveness  blca_oncogenesis  blca_survival  blca_basal_luminal
Genes
AARS             0.016052          0.078487       0.000000                 0.0
ABCB6            0.001612          0.027125      -2.890931                 0.0
ABCC5           -0.016742          0.002121       0.000000                 0.0
ABCF1           -0.038990         -0.028959      -0.496186                 0.0
ABCF3            0.023288          0.036671       0.000000                 0.0
...                   ...               ...            ...                 ...
ZNF395           0.000000          0.000000       0.000000                 0.0
ZNF451           0.011450          0.013403       0.000000                 0.0
ZNF586           0.000000          0.000000       0.119103                 0.0
ZNF589           0.000000          0.000000       0.000000                 0.0
ZW10            -0.042841          0.009722       0.000000                 0.0

[978 rows x 4 columns]

In [52]:
DPD_df = compute_invasiveness_score(blca, cluster1_t2, vector_name='lfc_mean', score_name='invasiveness')
display(DPD_df)

179
Index(['TSPAN6', 'FYN', 'TIMP2', 'DSG2', 'HERPUD1', 'RRP12', 'LAMA3',
       'TRAPPC3', 'HMG20B', 'MYLK',
       ...
       'ERO1A', 'TFDP1', 'HSD17B11', 'CTNND1', 'PSMB8', 'HLA-DRA', 'HSPA1A',
       'TSPAN4', 'CEBPD', 'HOXA10'],
      dtype='object', length=179)
         Unnamed: 1  proba_de  proba_not_de  bayes_factor    scale1    scale2  \
TSPAN6         3922    0.6782        0.3218      0.745512  0.000117  0.000153
FYN            2742    0.9240        0.0760      2.497979  0.000001  0.000002
TIMP2          3091    0.8906        0.1094      2.096884  0.000005  0.000010
DSG2           3251    0.8730        0.1270      1.927748  0.000202  0.000100
HERPUD1        3351    0.8606        0.1394      1.820282  0.000541  0.000521
...             ...       ...           ...           ...       ...       ...
HLA-DRA        2650    0.9314        0.0686      2.608396  0.000167  0.000349
HSPA1A         2313    0.9584        0.0416      3.137165  0.001365  0.000653
TSPAN4         2888    0.9112        0.0888      2.328376  0.000010  0.000009
CEBPD          3536    0.8280        0.1720      1.571519  0.000318  0.000543
HOXA10         2842    0.9154        0.0846      2.381427  0.000024  0.000033

         pseudocounts  delta  lfc_mean  lfc_median  ...  raw_mean1  raw_mean2  \
TSPAN6              0   0.25 -0.234558   -0.174375  ...   0.191852   0.816461
FYN                 0   0.25  1.402929    1.645311  ...   0.002786   0.007482
TIMP2               0   0.25  0.879282    0.711348  ...   0.006267   0.050616
DSG2                0   0.25  1.481517    1.683896  ...   0.329387   0.480034
HERPUD1             0   0.25  0.341497    0.416559  ...   0.941156   2.270567
...               ...    ...       ...         ...  ...        ...        ...
HLA-DRA             0   0.25  0.270814    0.260989  ...   0.240599   1.431018
HSPA1A              0   0.25  2.961610    2.732127  ...   2.386838   3.401609
TSPAN4              0   0.25  1.571823    1.440278  ...   0.016713   0.034971
CEBPD               0   0.25 -0.513269   -0.539379  ...   0.535515   2.702745
HOXA10              0   0.25  0.705842   -0.445707  ...   0.038997   0.179738

         non_zeros_proportion1  non_zeros_proportion2  raw_normalized_mean1  \
TSPAN6                0.171657               0.449704              1.135273
FYN                   0.002786               0.005322              0.014605
TIMP2                 0.006267               0.035331              0.039609
DSG2                  0.268802               0.303617              1.910272
HERPUD1               0.576950               0.737556              5.564504
...                        ...                    ...                   ...
HLA-DRA               0.193593               0.423776              1.483235
HSPA1A                0.832173               0.515125             13.587476
TSPAN4                0.016365               0.026008              0.104160
CEBPD                 0.386142               0.732114              2.952537
HOXA10                0.037256               0.146607              0.234211

         raw_normalized_mean2  is_de_fdr_0.05         comparison.1  \
TSPAN6               1.514426           False  cluster1_T2 vs Rest
FYN                  0.019602            True  cluster1_T2 vs Rest
TIMP2                0.105105           False  cluster1_T2 vs Rest
DSG2                 0.950849           False  cluster1_T2 vs Rest
HERPUD1              4.976633           False  cluster1_T2 vs Rest
...                       ...             ...                  ...
HLA-DRA              3.148683            True  cluster1_T2 vs Rest
HSPA1A               6.591985            True  cluster1_T2 vs Rest
TSPAN4               0.090061           False  cluster1_T2 vs Rest
CEBPD                5.367153           False  cluster1_T2 vs Rest
HOXA10               0.325824           False  cluster1_T2 vs Rest

              group1  group2
TSPAN6   cluster1_T2    Rest
FYN      cluster1_T2    Rest
TIMP2    cluster1_T2    Rest
DSG2     cluster1_T2    Rest
HERPUD1  cluster1_T2    Rest
...              ...     ...
HLA-DRA  cluster1_T2    Rest
HSPA1A   cluster1_T2    Rest
TSPAN4   cluster1_T2    Rest
CEBPD    cluster1_T2    Rest
HOXA10   cluster1_T2    Rest

[179 rows x 23 columns]
              TSPAN6       FYN     TIMP2      DSG2   HERPUD1     RRP12  \
ACH-001113  4.331992  2.797013  3.646163  6.329841  5.857235  4.771886
ACH-001289  4.567424  7.561708  5.256256  4.140779  7.183586  3.923149
ACH-001339  3.150560  6.518378  8.465077  5.095924  6.497772  3.682573
ACH-001538  5.085340  3.273516  5.365273  6.800771  5.951401  3.576522
ACH-000242  6.729417  2.996389  1.000000  5.508746  4.886550  4.263786
...              ...       ...       ...       ...       ...       ...
ACH-000285  0.056584  4.630522  0.815575  0.238787  5.168722  5.084490
ACH-002669  3.111031  1.560715  5.879461  6.405822  4.763943  4.865919
ACH-001858  4.390943  4.814038  8.788098  5.229203  6.102448  4.042644
ACH-001997  5.057450  5.101398  8.086508  6.483816  6.183288  4.398487
ACH-000052  4.249445  3.330558  6.179113  0.201634  5.154211  4.617651

               LAMA3   TRAPPC3    HMG20B      MYLK  ...     ERO1A     TFDP1  \
ACH-001113  2.157044  6.389739  5.574404  3.189034  ...  5.003602  5.790772
ACH-001289  1.704872  6.813781  4.372256  0.411426  ...  4.157044  6.607922
ACH-001339  0.505891  6.178515  5.524816  4.780310  ...  5.183089  6.760354
ACH-001538  5.074249  5.939697  5.408712  4.698774  ...  6.345716  6.535120
ACH-000242  3.679199  5.986638  5.740388  3.232661  ...  6.096979  6.715207
...              ...       ...       ...       ...  ...       ...       ...
ACH-000285  0.985500  6.021035  5.229203  0.275007  ...  4.273516  7.739646
ACH-002669  4.633431  5.740928  3.082362  1.292782  ...  6.723012  6.243555
ACH-001858  3.392317  6.672284  5.804260  6.023921  ...  5.651052  5.923862
ACH-001997  7.089901  6.249635  5.522307  0.659925  ...  5.384395  5.993221
ACH-000052  1.163499  6.088311  6.471513  1.111031  ...  4.723559  6.748998

            HSD17B11    CTNND1     PSMB8    HLA-DRA    HSPA1A    TSPAN4  \
ACH-001113  5.369466  5.728193  5.921960   0.263034  7.849124  3.130931
ACH-001289  6.132988  6.908333  0.084064   0.084064  4.778734  5.008541
ACH-001339  5.802969  5.478648  6.931210  10.273679  5.247168  6.616475
ACH-001538  5.980025  6.795455  7.651267   4.538538  7.664838  4.632850
ACH-000242  5.318317  7.017365  5.642124   2.077243  6.234770  1.948601
...              ...       ...       ...        ...       ...       ...
ACH-000285  4.287620  2.589763  5.655924  10.157347  1.956057  2.650765
ACH-002669  5.199672  6.334318  7.102973   0.863938  1.636915  5.259272
ACH-001858  4.816600  6.154413  6.942280   0.150560  6.972118  6.296090
ACH-001997  5.909293  6.199672  7.445843   0.565597  6.442280  3.867896
ACH-000052  3.075533  6.432458  5.925050   0.799087  6.431456  5.176722

               CEBPD    HOXA10
ACH-001113  2.003602  0.000000
ACH-001289  0.356144  0.622930
ACH-001339  1.807355  4.326250
ACH-001538  4.357552  0.042644
ACH-000242  3.440952  3.729009
...              ...       ...
ACH-000285  0.356144  3.416840
ACH-002669  2.310340  3.521051
ACH-001858  2.948601  3.240314
ACH-001997  2.835924  3.381283
ACH-000052  1.356144  0.176323

[1517 rows x 179 columns]

            invasiveness
ACH-001113    406.967028
ACH-001289    508.686023
ACH-001339    448.967134
ACH-001538    459.119477
ACH-000242    309.692170
...                  ...
ACH-000285    540.103101
ACH-002669    401.052197
ACH-001858    399.563435
ACH-001997    411.012767
ACH-000052    469.405228

[1517 rows x 1 columns]

In [53]:
cell_line_ids=['ACH-000142','ACH-000593','ACH-000396','ACH-000242','ACH-000384',
               'ACH-000018','ACH-000724']

DPD_cell_lines= DPD_df.loc[cell_line_ids]
DPD_cell_lines['cell_line_name']=['CAL29','BC3C','J82','RT4','SW780','T24','HT1376']
DPD_cell_lines
### Actually separated basal and luminal

            invasiveness cell_line_name
ACH-000142    329.278966          CAL29
ACH-000593    410.535269           BC3C
ACH-000396    385.801646            J82
ACH-000242    309.692170            RT4
ACH-000384    385.598630          SW780
ACH-000018    455.858153            T24
ACH-000724    488.622702         HT1376

In [82]:
cell_line_ids=['ACH-000473','ACH-000142','ACH-000593','ACH-000396','ACH-000242','ACH-000384',
               'ACH-000018','ACH-000724','ACH-001407','ACH-000753']

DPD_cell_lines= DPD_df.loc[cell_line_ids]
DPD_cell_lines['cell_line_name']=['RT112','CAL29','BC3C','J82','RT4','SW780','T24','HT1376','UMUC13','JMSU1']
DPD_cell_lines

            invasiveness cell_line_name
ACH-000473    326.644998          RT112
ACH-000142    329.278966          CAL29
ACH-000593    410.535269           BC3C
ACH-000396    385.801646            J82
ACH-000242    309.692170            RT4
ACH-000384    385.598630          SW780
ACH-000018    455.858153            T24
ACH-000724    488.622702         HT1376
ACH-001407    442.928028         UMUC13
ACH-000753    459.535752          JMSU1

In [83]:
DPD_cell_lines.sort_values('invasiveness')

            invasiveness cell_line_name
ACH-000242    309.692170            RT4
ACH-000473    326.644998          RT112
ACH-000142    329.278966          CAL29
ACH-000384    385.598630          SW780
ACH-000396    385.801646            J82
ACH-000593    410.535269           BC3C
ACH-001407    442.928028         UMUC13
ACH-000018    455.858153            T24
ACH-000753    459.535752          JMSU1
ACH-000724    488.622702         HT1376

In [69]:
DPD_cell_lines.columns = ['basal_luminal','cell_line_name']

In [71]:
DPD_cell_lines.sort_values('basal_luminal')

            basal_luminal cell_line_name
ACH-000242     309.692170            RT4
ACH-000142     329.278966          CAL29
ACH-000384     385.598630          SW780
ACH-000396     385.801646            J82
ACH-000593     410.535269           BC3C
ACH-000018     455.858153            T24
ACH-000724     488.622702         HT1376

In [ ]:
###

In [49]:
cell_line_ids=['ACH-000142','ACH-000593','ACH-000396','ACH-000242','ACH-000384',
               'ACH-000018','ACH-000724']

DPD_cell_lines= DPD_df.loc[cell_line_ids]
DPD_cell_lines['cell_line_name']=['CAL29','BC3C','J82','RT4','SW780','T24','HT1376']
DPD_cell_lines

            invasiveness cell_line_name
ACH-000142     -2.123590          CAL29
ACH-000593     -0.175572           BC3C
ACH-000396     -1.372428            J82
ACH-000242     -2.673644            RT4
ACH-000384     -2.476201          SW780
ACH-000018     -1.622554            T24
ACH-000724     -2.513163         HT1376